#!/usr/bin/env python3

import sys

if sys.version_info[0] < 3 or sys.version_info[1] < 7:
    print("This program requires Python version 3.7 or newer")
    sys.exit(1)

if __name__ == '__main__':
    from lib.main import main
    main()
