= How To Guides

This document describes a number of common operations for quick reference.


== Creating a workspace

You may create an empty workspace with:

[source,shell]
----
wit init <workspace>
----


== Initializing a workspace with an existing repository

If you want to specify one or more packages when you create the workspace, you can use the `-a` option:

[source,shell]
----
wit init <workspace> -a </path/to/git/repo/soc.git>[::revision]
----

The revision can be a tag, branch, or commit.
Note that wit respects normal git behavior.
You may also specify the `-a` multiple times in the same command.


== Adding a package to a workspace

To add a package to a workspace that has already been created you use the `add-pkg` sub-command.

[source,shell]
----
wit add-pkg </path/to/git/repo/soc.git>[::revision]
----


== Resolve and fetch package dependencies

Once you have added one or more repositories to your workspace, you can use `update` to resolve and fetch
the transitive dependencies of each package.

[source,shell]
----
wit update
----


== Updating a package

You can update the revision of a package in the workspace using the `update-pkg` sub-command.

[source,shell]
----
wit update-pkg <package>[::revision]
----

If you update to `<package>::<branch>`, it will check out the local version of that branch.
You can always check out remote branches by specifying the remote as well

[source,shell]
----
wit update-pkg <package>::<remote>/<branch>
----


== Viewing dependency graph visually

Wit comes with two ways of visualizing the dependency graph,
one that can be printed directly on the terminal in ASCII format and one that can be rendered as an SVG image.

To print out the dependency on the command line, run:

[source,shell]
----
$ wit inspect --tree
api-scala-sifive::4fd0852
└─wit::298410a0
----

Wit can also generate a https://en.wikipedia.org/wiki/DOT_(graph_description_language)[DOT] file,
which can be then rendered into an image with a number of different tools,
https://graphviz.org/[Graphviz] being one of the most prominent.

If you have Graphviz installed, then the following commands will produce an SVG image of the Wit dependency graph:

[source,shell]
----
wit inspect --dot | dot -Tsvg > graph.svg
----

This SVG file can be directly viewed in most web browsers.


== Restore a previous workspace

If you have a matching pair `wit-lock.json` and `wit-workspace.json` from another workspace, you can create
a new clean workspace by pointing at the previous workspace via the `restore` sub-command.

    $ wit restore -n <new-workspace-name> -w $OTHER_WS

Dependencies are only specified by the `wit-lock.json` file, no other dependency resolution is performed.
If you are keeping your wit-lock.json and wit-workspace.json under revision control you can do an in-place
restore

    $ git clone http://example.com/my_workspaces
    $ cd my_workspaces/project1
    $ ls
    wit-lock.json wit-workspace.json
    $ wit restore

== Specify dependencies via git submodules

Some repositories that you would like to use as a dependency already use git submodules.
Wit can read the git subomodule metadata from the repository as if it were a `wit-manifest.json`
file.
Wit will only read submodule data when there is no `wit-manifest.json` file.

This is intended as a convenience only. While wit can *read* the depencency metadata
it can not *write* the metadata. So functionality like `wit update-dep` will not update
submodule metadata in those particular repositories, while otherwise still functioning
normally in other dependency repositories.

== Ignore git submodules

=== Ignore all git submodules

Provide a valid `wit-manifest.json` file.
This can be produced when using `wit add-dep` if you have a dependency to add.
Otherwise, you can provide a wit-manifest.json file containing only `[]`.

=== Ignore a specific git submodule

In a `.gitmodules` file within your repository, you can add a line
to the git submodule: `wit = ignore`

    $ cat workspace/foo/.gitmodules
    [submodule "baa"]
        path = baa
        url = https://github.com/baa-corp/baa.git
        wit = ignore

This is only a local effect, it's the equivelant of deleting an entry in the `wit-manifest.json`.
If another repository were to have `baa` as a dependency without a `wit = ignore` then `baa`
will still appear in the workspace, but the metadata for which revision to use will ignore the
input of `foo`
