#!/bin/sh

wit_repo='git@github.com:sifive/wit'
test_root=$(dirname $(realpath $0))
wit_root=$(realpath $test_root/..)

export PATH=$wit_root:${PATH}

regression_dir=${wit_root}/regression.`date -Iseconds`
echo "Running tests in ${regression_dir}"
mkdir $regression_dir

declare -A test_results
regression_result=0
for test_path in $test_root/*.t; do
        cd $regression_dir
        test_name=$(basename $test_path)
        echo "Running test [$test_name]"
        mkdir $test_name
        cd $test_name

        $test_path
        if [ $? -eq 0 ]; then
                test_results["$test_name"]="PASS"
        else
                test_results["$test_name"]="FAIL"
                regression_result=1
        fi
done

for test_name in ${!test_results[@]}; do echo "${test_name} - ${test_results[$test_name]}"; done
